### ISSUE TITLE
SLZ-URP Materials not receiving textures applied after all instructions in wiki have been followed. 

### ISSUE THREAD

**Issue by Floofbutt** [StressLevelZero/MarrowSDK#10]
All  SLZ-URP materials show as a blank magenta palette or a black/magenta checkerboard despite having color maps assigned to them.  I have attempted updating all unity packages, as well as starting a new project from scratch making sure to follow all listed instructions in the wiki.

Windows build support IL2CPP is installed.

The listed OpenXR fixes do not appear in unity anymore. 

Not sure how or why but this is my second time installing the SDK on a new project and the second time this has happened. 

There is no errors on the console in unity

**Comment by Floofbutt** [comment]
Quick update, I think the issue I'm having is due to the current version of unity 2021.3.5fq requiring a URP global settings profile that isn't included with the SLZ universal RP? The 3dURP template is nonexistent for me So i assume this is the best way to resolve the issue. 
![1090f6b6bee447c4dbc0903b60a81e24](https://user-images.githubusercontent.com/114708743/193332009-88f24a34-083d-4d6f-936f-5af82db560ef.png)

**Comment by KevinComerford** [comment]
You need to update the hub to access the supported template.

**Comment by KevinComerford** [comment]
You need to update your hub to access the supported template.
