### ISSUE TITLE
issue importing required packages into unity (resolved)

### ISSUE THREAD

**Issue by wilbursmells** [StressLevelZero/MarrowSDK#13]
new to all of this so sorry if there's a simple fix i just don't know about. 
when attempting to import any of the required packages i get an error message.

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/StressLevelZero/Custom-RenderPipelineCore.git ]:
  Error when executing git command. fatal: unable to access 'https://github.com/StressLevelZero/Custom-RenderPipelineCore.git /': URL using bad/illegal format or missing URL
 [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

i  just installed unity and git and followed each step, would just like some help. :)

actually i figured it out, instead of triple clicking to select all to copy and then paste, i had to drag my cursor to select it all and then that fixed it for some reason. thanks if you took the time to read!

**Comment by dotbenj** [comment]
Can you try to clone the repo manually in your git console :
`git clone https://github.com/StressLevelZero/Custom-RenderPipelineCore.git`
maybe it will give your more insight of your issue.

Tuto to clone repo on windows :
https://youtu.be/e5kQ_Gx_qrs
