### ISSUE TITLE
Error imporrting Custom-URP package from Github

### ISSUE THREAD

**Issue by FarmingSoulz** [StressLevelZero/MarrowSDK#19]
Following the wiki guide, I have installed the 2 other packages but the Custom URP package repeatedly creates error codes and fails to install (image attached).
Any ideas on what could resolve this issue? 
![Screenshot 2022-10-01 013037](https://user-images.githubusercontent.com/114785252/193375811-95346a6b-845c-4657-a427-ff3ed175413d.png)

**Comment by dotbenj** [comment]
Have you imported this one first:
`https://github.com/StressLevelZero/Custom-RenderPipelineCore.git`

**Comment by KevinComerford** [comment]
Make sure you're in the right unity version

**Comment by FarmingSoulz** [comment]
> Have you imported this one first: `https://github.com/StressLevelZero/Custom-RenderPipelineCore.git`?

I can confirm I have already successfully installed 2 other packages as shown on the right side of the screenshot.

**Comment by FarmingSoulz** [comment]
> sure



> Make sure you're in the right unity version

Thank you.
