### ISSUE TITLE
Invalid Asset Reference

### ISSUE THREAD

**Issue by Eidenz** [StressLevelZero/MarrowSDK#22]
I followed the avatar tutorial and all I'm getting is "Invalid Asset Reference" when trying to create the Crate for my avatar.

I'm used to creating VRC avatar, and the tool isn't verbose at all so I have no idea why this shows up.

**Comment by Myrkie** [comment]
hello when creating an avatar you must first drag the avatar into your assets folder and then select "original prefab" after this drag the newly created prefab in your assets folder into the same dialog for create a crate.

**Comment by Eidenz** [comment]
That's what I was doing already. But I noticed that if I do it twice in a row, I finally get the message asking for original prefab, fixing the issue.

No idea why I have to do it twice tho, but as long as it works that's fine by me
