### ISSUE TITLE
Cannot Switch to Avatar and preview becomes glitched.

### ISSUE THREAD

**Issue by Lyvery** [StressLevelZero/MarrowSDK#23]
After following all of the steps to make the avatar and import it, once in game when I try to switch to the avatar it wont let me. There's no avatar preview above the screen and when I click confirm, nothing happens. Then, once I try to switch to a new avatar, I see the avatar I created merged with the selected avatar in the avatar preview. 

Unsure if this is an issue with the SDK, a bug in Bonelab or an issue on my part but I've seen numerous others have this issue. If anyone has any ideas I'd appreciate it. 

![image](https://user-images.githubusercontent.com/114788408/193378931-55f6da62-1e30-41c2-880a-ce0686039d05.png)
![image](https://user-images.githubusercontent.com/114788408/193378937-c6d6ff35-2387-4fe5-8da6-2a79d0cc46f6.png)

**Comment by Torterenek** [comment]
This was only one avatar? I had the issue with my second avatar in the pallet, while the first one was fine.

**Comment by NabsiYa** [comment]
I also have issues with the avatar not working at all it's weird.

**Comment by RyusoA** [comment]
I'm also having this issue, no fixes I've tried seem to work, some say you just need to keep remaking the pallet and crate and prefab or some variation until it works

**Comment by FireDorn6073** [comment]
same issue here; this happened on my second pallet
my first pallet was fine with both of the avatars it had in it
but the new pallet, on a different unity project was having this issue

**Comment by RyusoA** [comment]
I got a fix: Make sure all bones have a slot in, if it gives an error for those bones they need some form of place holder at the least even if you're told they arent required, in my case I had no Toes or some parts of fingers, once i just made new parts in blender and filled the slots it worked perfectly

**Comment by FireDorn6073** [comment]
> I got a fix: Make sure all bones have a slot in, if it gives an error for those bones they need some form of place holder at the least even if you're told they arent required, in my case I had no Toes or some parts of fingers, once i just made new parts in blender and filled the slots it worked perfectly

this seemed to work; I was using an older fbx of my model which had a few rigging issues without knowing it after putting the new version in and listing the bones it worked but only after making a new pallet for some reason
