### ISSUE TITLE
Not in git directory error

### ISSUE THREAD

**Issue by Apollyon822** [StressLevelZero/MarrowSDK#47]
Get an error every time I try and import the links
Not in git directory error

![Screenshot 2022-10-02 113956](https://user-images.githubusercontent.com/114870704/193462712-87a8fc95-a645-436e-93ac-63bee23771ef.png)

**Comment by PlasticChair1** [comment]
i get that too

**Comment by Ferripro321** [comment]
Are you using the correct unity version, do you have git installed on your PC?

1) Make sure the unity version is 2021.3.5f1
2) Install git from: https://git-scm.com/download/win (installer x64 one)

**Comment by Apollyon822** [comment]
I have done both of those things and its still not working, any other tips?

**Comment by Linisaperson** [comment]
I have the same issues.

**Comment by Apollyon822** [comment]
I was able to fix the problem by reinstalling unity, the project, and git on the main driver of my computer. its running fine now.
