### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by KillerKaneoss** [StressLevelZero/MarrowSDK#53]
Whenever I try to import it to unity, it doesnt work, it just says import failed... How do i fix this?

**Comment by puttehi** [comment]
This is very little information but ensure you have deleted the extra trailing space from the URLs after pasting them to Unity Package Manager. Also ensure you have Git installed.

**Comment by reddeath43** [comment]
how do you install git

**Comment by valentinegb** [comment]
> how do you install git

Please make a new issue for questions like this. (But to answer your question, git can be installed [here](https://git-scm.com/downloads).)

**Comment by yewnyx** [comment]
Ensuring you have git properly installed is a good idea, however this issue doesn't have any actionable information. Closing.
