### ISSUE TITLE
Vanilla spawnables are not in the asset wharehouse

### ISSUE THREAD

**Issue by SpiredFormula** [StressLevelZero/MarrowSDK#54]
I can’t find any of the vanilla bonelab spawnables like guns, enemies, etc in the asset wharehouse. Am I missing something or are they just not there yet?

**Comment by valentinegb** [comment]
There's a pallet you can download in the Lava Gang Discord, I think it's still being updated but it should have most of that stuff.

https://discord.gg/dhDFWP3Y

**Comment by SpiredFormula** [comment]
thanks for the help wish it was more clear on the documentation

**Comment by valentinegb** [comment]
> thanks for the help wish it was more clear on the documentation

Yeah I agree, you should be able to download it right from the documentation, or at least link to the Discord from there. Both, would be ideal.
