### ISSUE TITLE
Non-convex mesh colliders on spawnables simply don't work

### ISSUE THREAD

**Issue by technobaboo** [StressLevelZero/MarrowSDK#63]
In-game, mesh colliders without the convex property simply fall right through the floor... while mesh colliders aren't optimal they are necessary for ring shapes.

In editor, mesh colliders do not contribute to collider bounds unless they are convex. I don't see why this would be the case unless mesh colliders' bounds in GenerateColliderBounds are none?

**Comment by camobiwon** [comment]
Unity / PhysX does not support concave mesh colliders on rigidbodies. You will have to create these out of primitive and / or segmented convex mesh colliders.
