### ISSUE TITLE
 Error when executing git command. fatal: not in a git directory

### ISSUE THREAD

**Issue by Brax37** [StressLevelZero/MarrowSDK#66]
I get this issue for every single one I try to put in, tried looking it up nothing popped up, any fixes?
![image](https://user-images.githubusercontent.com/111468129/193877098-91156208-875c-4fbd-9e4b-74fd53890182.png)

**Comment by FrostyTheHuman** [comment]
Install [Git](https://git-scm.com/downloads) and restart Unity. If that doesn't work, restart your PC.
