### ISSUE TITLE
Assembly 'SLZ.Serialize' error

### ISSUE THREAD

**Issue by XanderDevelops** [StressLevelZero/MarrowSDK#67]
When I enter the URL in package manager it shows me this error: 

Assembly 'SLZ.Serialize' with identity 'SLZ.Serialize, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json' with identity 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

**Comment by yewnyx** [comment]
Please ensure your Unity version is 2021.3.5f1.

**Comment by XanderDevelops** [comment]
Ahh ok, I am using 2021.2.12f1, I will update it then. Thanks
