### ISSUE TITLE
avatar stuck in sitting pose, cant walk or jump. anyone has a fix?

### ISSUE THREAD

**Issue by TemaStar** [StressLevelZero/MarrowSDK#69]
please help meeeeeeee

**Comment by TemaStar** [comment]
i didnt make custom sounds is it okay

**Comment by TemaStar** [comment]
![20221005214247_1](https://user-images.githubusercontent.com/69725988/194138065-51a6ed1b-e8a8-4145-8e72-be1d4c8d2560.jpg)
this happens every time and he wont move

**Comment by yewnyx** [comment]
I recommend going to our discord for avatar help.
