### ISSUE TITLE
Avatar not selectable in body mall / won't load

### ISSUE THREAD

**Issue by valentinegb** [StressLevelZero/MarrowSDK#70]
The avatar I made isn't selectable in the body mall. When I click the name, it makes a ui sound but it doesn't show the model above the body mall, it doesn't show the stats, and when I click Apply (or whatever the button at the bottom is I can't remember lol) it doesn't switch my current avatar.

I'm really not sure what I did wrong here- it's probably something silly. Here's all the information I think could be relevant:

### Body
![Screenshot 2022-10-05 at 5 43 15 PM](https://user-images.githubusercontent.com/35977727/194188804-fa70abea-f987-48e0-8eee-467098b8cfe3.png)
![Screenshot 2022-10-05 at 5 44 02 PM](https://user-images.githubusercontent.com/35977727/194188871-220311bd-5002-49ea-a2cf-7858cbaa28e5.png)
### GameObject
![Screenshot 2022-10-05 at 5 51 39 PM](https://user-images.githubusercontent.com/35977727/194189529-f63306f8-5e3d-4afb-af12-46dd6a21b40e.png)
![Screenshot 2022-10-05 at 5 52 42 PM](https://user-images.githubusercontent.com/35977727/194189619-55bd3b41-984c-4126-b5f1-404fd11e6123.png)
### Prefab hierarchy
![Screenshot 2022-10-05 at 5 44 37 PM](https://user-images.githubusercontent.com/35977727/194188929-35e32cae-cb5f-4989-b0b0-19d17bb00bc1.png)
### Humanoid Avatar Definition
![Screenshot 2022-10-05 at 5 45 25 PM](https://user-images.githubusercontent.com/35977727/194189006-855baac8-0e0d-4a82-8410-ca90d3f28bc7.png)
![Screenshot 2022-10-05 at 5 45 46 PM](https://user-images.githubusercontent.com/35977727/194189039-b6fd41a6-1561-4e0c-8d86-2279be1c294b.png)
![Screenshot 2022-10-05 at 5 46 00 PM](https://user-images.githubusercontent.com/35977727/194189060-c8c7b24a-8701-4953-89ca-bf302680e527.png)
![Screenshot 2022-10-05 at 5 46 10 PM](https://user-images.githubusercontent.com/35977727/194189072-ea60c9bc-3455-49b3-af58-7aa9be2af154.png)
### Avatar Assets
![Screenshot 2022-10-05 at 5 47 08 PM](https://user-images.githubusercontent.com/35977727/194189148-99835432-ae58-484f-ac98-548e84efc2c0.png)
![Screenshot 2022-10-05 at 5 47 19 PM](https://user-images.githubusercontent.com/35977727/194189164-114f4a86-18f4-4f19-9b76-518db5501560.png)
![Screenshot 2022-10-05 at 5 47 39 PM](https://user-images.githubusercontent.com/35977727/194189185-e7b661e8-cc41-4fc6-96e0-5aab6c4cc3f6.png)
### Avatar Crate
![Screenshot 2022-10-05 at 5 53 48 PM](https://user-images.githubusercontent.com/35977727/194189722-14e55865-c039-4098-9fc3-89ca8b702037.png)

Whew! Sorry there's so much- if you need any other info let me know.

**Comment by valentinegb** [comment]
> am just a fellow avatar modder (not actual support but I will try)
> 
> 
> 
> Eye center override slider is maxed out, normally never need to be more than 0.10

Even maxed out, the green dot is still inside Mario's head :/
And could that really mess everything up like that? That sounds like an error in the SDK, not from me, if it is the cause of this

**Comment by Strazyplus** [comment]
Where is the Eye center override at? 

Just in case... double check you are saving the prefab and using the prefab instead of the fbx. When making crate.

-----------------


also a tip that has nothing to do with the problems you are having. 
You can change the scale of the head vertically as well but must do it within the script. which means the hitbox for your head can be sized to the chin.
![image](https://user-images.githubusercontent.com/6706750/194192790-49cf928f-8bb5-46d7-b592-cf9a2a5fe704.png)

**Comment by valentinegb** [comment]
Oh- that tip is useful haha thanks!

The eye center override is aligned with the head vertically, I assumed I couldn't align it horizontally since there's an offset slider

**Comment by Strazyplus** [comment]
Empty is a 3D point, the offset is manly for tweaking without having to open prefab and move it manually. You can set the offset to zero and just position the empty exact. 

Heres how I did mine
![image](https://user-images.githubusercontent.com/6706750/194193902-588e06a6-57e4-479c-acb2-f7e610eb5cf7.png)

**Comment by valentinegb** [comment]
Okay, I'll try that next time on my computer

**Comment by yewnyx** [comment]
I think it's awesome that y'all are helping each other troubleshoot! 😃 

With that said, troubleshooting content authoring is outside the scope of this GitHub repository's purpose. If you'd like further help with content authoring, the official discord may be a more suitable venue?
