### ISSUE TITLE
Hands are messed up

### ISSUE THREAD

**Issue by DarkenedSNIP3R** [StressLevelZero/MarrowSDK#74]
The hands on my avatar are messed up but are fine in blender and unity. 

![20221006233906_1](https://user-images.githubusercontent.com/115172623/194431899-fed8b16d-27b1-4b15-93ce-b6913aa8c2af.jpg)
![image](https://user-images.githubusercontent.com/115172623/194431946-ab0d3c54-e902-4d6a-856c-1cbb21517b58.png)
![image](https://user-images.githubusercontent.com/115172623/194432124-2e5e9c18-ac7f-4e52-bb15-9e0cb69e4b92.png)

**Comment by yewnyx** [comment]
Unfortunately, we aren't monitoring the SDK repository's GitHub for content authoring issues.

Our official discords may be able to offer you assistance.
