### ISSUE TITLE
Spawnables manual mode with extra references

### ISSUE THREAD

**Issue by DevynCole** [StressLevelZero/MarrowSDK#75]
Discovered the `NotImplementedException()` return when calling `PlaceSpawnable()` via ultevents. Would love to be able to easily reference a rigidbody attatched to a spawnable once its placed. For example, I'm trying to build a baseball pitching machine. Ideally, I'd call `placeSpawnable()` and then reference the spawned baseball's rigidbody, and add force to it. Instead, I'm attempting to instantiate a gameobject with the spawnable crate placer on it and its reference already set due to lack of other options, and then adding force to a plunger on my pitching machine with a configurable joint to push the baseball. Instantiating the spawnable through ultevents doesn't work, and then my plunger clips right through the ball I'd already placed.

**Comment by yewnyx** [comment]
While the SDK allows one to add references to callable methods, it does not actually contain the implementation. I recommend testing your content in-game.
