### ISSUE TITLE
Unable to become avatar and preview issue

### ISSUE THREAD

**Issue by PickleJimy** [StressLevelZero/MarrowSDK#80]
![bad](https://user-images.githubusercontent.com/115375570/194727712-c36dd786-7205-4f2e-b2ee-809e30ff752f.png)

When I try to become my avatar I am unable too and I tried to see what there was wrong and I have all the bones needed.

**Comment by yewnyx** [comment]
My apologies - we aren't monitoring the SDK's GitHub repository for content authoring issues.

Perhaps asking for help in one of our discords may bear fruit?
