### ISSUE TITLE
Items not grabbable!

### ISSUE THREAD

**Issue by Vitorixx** [StressLevelZero/MarrowSDK#85]
How can I make Items grabbable? Seen some weapons already on mod io which are grabable but I wonder how they accomplished that. And I know that custom items arent supposed to be supported yet.

**Comment by PSYCHOdk1** [comment]
I want to know that too.

**Comment by Vitorixx** [comment]
I found it out already. The lava gang discord has plenty of information on how to make items grabbable. You need an unofficial extended sdk which you can get from here https://github.com/RevOcelotMGS/Marrow-ExtendedSDK there is also a quite helpful documentation I also found on that discord https://docs.google.com/document/d/1vKh0Hd_l0zD8FCiKP27aOnkaCqO0hh3El5R8wy93I4A/edit
