### ISSUE TITLE
Unable to edit the body 

### ISSUE THREAD

**Issue by Neongravity** [StressLevelZero/MarrowSDK#91]
It will not let me edit the body on my custom avatars everything works fine until the edit body button. I click it and nothing happens it does not give me an error either

**Comment by valentinegb** [comment]
Does the avatar script show that you're missing any bones? Also, do you see a red dot gizmo floating next to your avatar?

**Comment by Neongravity** [comment]
I see the red dot next the avatar it does say I'm missing wrist bones but it also says it should be fine

**Comment by Neongravity** [comment]
Fixed it I does not automatically set the hand as the wrist bone you have to do it manually

**Comment by valentinegb** [comment]
Glad you found a solution. Could you close your GitHub issue please?
